---
title = "calculus-trig-derivs"
---

&nbsp;

# <u>Derivatives Of Trigonometric Functions</u>

&nbsp;


### <u>Table of Contents</u>

&nbsp;

* Exponential Functions: A Brief Review
* The Derivative of An Exponential Function
* Examples

&nbsp;

### <u>Exponential Functions: A Brief Review</u>

&nbsp;

An exponential function is a function of the form:

$$\displaystyle a^{x}$$

where $a$ is a non-zero number and $x$ is a variable.

One should be careful and make the distinction between an exponential function such as $2^x$ versus a polynomial such as $x^2$ which is a variable to a numeric power/exponent.

&nbsp;

### The Derivative of An Exponential Function

&nbsp;

If we are given $f(x) = a^{g(x)}$ where $g(x)$ is a different function of $f(x)$. The derivative of $f(x)$ is:

$$\displaystyle \begin{array} {lcl} f'(x) & = & \text{ln}(a) \cdot a^{g(x)} \cdot \dfrac{d}{dx} g(x) \\ & = & \text{ln}(a) \cdot a^{g(x)} \cdot g'(x) \end{array} \\ $$

Note that this general formula does use a variation of the chain rule. Since the exponent is a function of x, we take the derivative of the exponent as well.

Given the more common case of $g(x) = x$ in the exponent, the general case becomes:

$$\displaystyle \begin{array} {lcl} f'(x) & = & \text{ln}(a) \cdot a^{x} \cdot \dfrac{d}{dx} x \\ & = & \text{ln}(a) \cdot a^{x} \cdot (x)' \\ & = & \text{ln}(a) \cdot a^{x} \cdot 1 \\ & = & \text{ln}(a) \cdot a^{x} \\ \end{array} \\ $$

If we are given $e$ as the base such that we have $f(x) = \text{e}^{g(x)}$. The derivative $f'(x)$ will be as follows:

$$\displaystyle \begin{array} {lcl} f'(x) & = & \text{ln}(a) \cdot \text{e}^{g(x)} \cdot \dfrac{d}{dx} g(x) \\ & = & \text{ln}(e) \cdot \text{e}^{x} \cdot g'(x) \\ & = & 1 \cdot \text{e}^{x} \cdot g'(x) \\ & = & \text{e}^{x} \cdot g'(x) \\ \end{array} \\ $$

(Note that ln(e) = 1 as $e^{1} = e$.)

A special case is where $f(x) = \text{e}^{x}$

In this case we have $a = e$ and $g(x) = x$. The derivative of $\text{e}^{x}$ is simply $\text{e}^{x}$.

&nbsp;

### <u>Examples</u>

&nbsp;

**Example One**

Given $f(x) = \text{e}^{2x}$, what is $f'(x)$?

&nbsp;

$$\displaystyle \begin{array} {lcl} f'(x) & = & \text{ln(e)} \cdot \text{e}^{2x} \cdot \dfrac{d}{dx} 2x \\ & = & 1 \cdot \text{e}^{2x} \cdot 2 \\ & = & 2 \cdot \text{e}^{2x} \\ \end{array} $$

&nbsp;

**Example Two** 

$f(x) = 2 \cdot \text{e}^{x}$

$$ \displaystyle \begin{array} {lcl} f'(x) & = & 2 \cdot \dfrac{d}{dx} \text{e}^{x} \\ & = & 2 \cdot \text{e}^{x} \\ \end{array}$$

&nbsp;

**Example Three** 

$f(x) = 5^{x}$

$$\displaystyle \begin{array} {lcl} f'(x) & = & \text{ln(5)} \cdot 5^{x} \cdot \dfrac{d}{dx} x \\ & = & \text{ln(5)} \cdot 5^{x} \cdot 1 \\ & = & \text{ln(5)} \cdot 5^{x} \\ \end{array} $$

&nbsp;

**Example Four** 

$f(x) = 10^{\text{sin}(x)}$

$$\displaystyle \begin{array} {lcl} f'(x) & = & \text{ln(10)} \cdot 10^{\text{sin}(x)} \cdot \dfrac{d}{dx} \text{sin}(x) \\ & = & \text{ln(10)} \cdot 10^{\text{sin}(x)} \cdot \text{cos}(x)\\ \end{array} $$

The featured image is from http://www.emathhelp.net/images/calc/1_2_exponential_function.png.