---
title: "Crypto Related Items"
output: html_document
---

&nbsp;

**Started on July 25, 2021**


This page features some works and information from me related to cryptocurrencies. I am somewhat new to the space and will continue to learn. 

**Do invest and trade cryptos, stocks and the likes at your own risk.**

---

### Contents

* <a href="#crypto_articles">Articles, Opinion Pieces</a>

* <a href="#python_crypto">Python Crypto Projects</a>

* <a href="#r_crypto">R Crypto Projects</a>

&nbsp;

<a name="crypto_articles"></a>

### Articles, Opinion Pieces

&nbsp;

* [Notes on Stablecoins](./stableCoins_notes.html)
* [Canada Crypto Offerings As Of September 2021](./canadaCryptos_sept2021.html)
* [Cryptos With Low Transaction Fees](./lowCost_cryptos.html)
* [Decentralized Finance (DeFi) As Do It Yourself (DIY) Crypto](./defi_DIYCrypto_website.html)

&nbsp;

---

<a name="python_crypto"></a>


### Python Crypto Projects

&nbsp;

[Binance For Crypto Data & Candlestick Charts In Python](https://github.com/dk81/crypto_python/blob/main/binance_crypto_data.ipynb)

The python-binance package along with mplfinance was used to obtain cryptocurrency information from Binance. A candlestick price chart for the BTCUSDT trading pair was produced. 

&nbsp;

[Coinbase Crypto Data In Python & Candlestick Price Charts](https://github.com/dk81/crypto_python/blob/main/coinbase_cryptodata_python.ipynb)

Python being used to extract Coinbase crypto price data with the Coinbase API.

&nbsp;


[Crypto Fear & Greed Index Data In Python](https://github.com/dk81/crypto_python/blob/main/feargreed_stockscrypto.ipynb)

Using Python to extract cryptocurrency fear and greed index data and plotting the index values in a line plot.

&nbsp;

[Kucoin Crypto Data & Candlestick Charts In Python](https://github.com/dk81/crypto_python/blob/main/kucoin_crypto_python.ipynb)

This project is similar to the Binance crypto data project. The Kucoin crypto exchange API is used to connect to Python. Candlestick price charts are produced with the mplfinance Python library.

&nbsp;


[Bitcoin Line Plots On Price & Marketcap In Python](https://github.com/dk81/crypto_python/blob/main/bitcoin_price_mcap_plots.ipynb)

Python and plotly to plot simple line plots on Bitcoin's historical price and marketcap.

&nbsp;

[Yahoo Finance For Stocks & Crypto In Python](https://github.com/dk81/crypto_python/blob/main/yahoo_finance_python_stocks_crypto.ipynb)

Exploring the `yfinance` package in Python and plotting prices of stocks & cryptocurrency.

&nbsp;

[Coingecko Price Data Webscrape In Python](https://github.com/dk81/crypto_python/blob/main/coingecko_crypto_webscrape.ipynb)

Using Python and BeautifulSoup to webscrape cryptocurrency prices from the Coingecko website.


&nbsp;

---

<a name="r_crypto"></a>

### R Crypto Projects

&nbsp;

[Crypto Prices Dashboard With Crypto Fear & Greed Index In R](https://dkmathstats.shinyapps.io/cryptoPrices_R)

This interactive dashboard produced in R, RShiny and flexdashboard features crypto prices from Coinbase and Kraken. There is a crypto fear and greed index where the data is extracted from [alternative.me](https://alternative.me/crypto/fear-and-greed-index/). You can find available price data for many of the popular cryptocurrencies along with a good handful of altcoins.

&nbsp;

[Quandl Financial Data - Bitfinex Crypto Price Data In RShiny](https://dkmathstats.shinyapps.io/quandl_financedata_app/)

In late July 2021, I have included a new section in my Quandl Financial Data RShiny app. This new section features crypto price data from the Bitfinex crypto exchange. The free datasets are from Quandl's website. 

&nbsp;


[Coinbase Crypto Data In R & Candlestick Price Charts](./Rcoinbase_candlestickCharts.html)

This [reference page](https://www.cryptodatadownload.com/blog/how-to-download-coinbase-price-data-R.html) contains a nice script on extracting cryptocurrency data into R and writing the data into a `.csv` file. I wanted to go a few steps further by modifying the script for user input.

&nbsp;


[Kraken Crypto Data Into R](./RKraken_cryptopriceCharts.html)

Like the Coinbase project in R, I obtain data from the Kraken exchange. I add a second plot for the Relative Strength Indicator (RSI) measure.

&nbsp;

[Crypto Fear & Greed Index Data In R](./feargreed_crypto.html)

Using R to obtain fear and greed index data and plotting the index values over time in `plotly`.

&nbsp;

[The `coinmarketcapr` Package In R For Crypto Data](./coinmarketcap_Rpage.html)

In this page, I explore the `coinmarketcapr` R package for obtaining crypto data. Note that I use the free API service.

&nbsp;
