---
title: "dkmathstats Website"
---

&nbsp;

Hi there. Welcome to my website. Topics include mathematics, statistics, R programming, Python programming with data science.

This site is run with R Markdown with the use of this [guide](http://nickstrayer.me/RMarkdown_Sites_tutorial/).

I have more items such as R and Python code from my Github [here](https://github.com/dk81).

---

**Starting on July 25, 2021, I am seeking a (remote) job in the cryptocurrency space. The ideal would be a position in data analysis with crypto.**

---

**Contact**

- __Name:__ David
- __E-Mail:__ dku8691@protonmail.com

---

**R Shiny Projects**

&nbsp;

[Crypto Prices Dashboard With Crypto Fear & Greed Index](https://dkmathstats.shinyapps.io/cryptoPrices_R)

This interactive dashboard produced in R, RShiny and flexdashboard features crypto prices from Coinbase and Kraken. There is a crypto fear and greed index where the data is extracted from alternative.me. You can find available price data for many of the popular cryptocurrencies along with a good handful of altcoins.

&nbsp;

[Quandl Finance R Shiny Web Application](https://dkmathstats.shinyapps.io/quandl_financedata_app/)

In this RShiny web application, I use R, RShiny and Quandl to present various financial data. The datasets that are used are free and cover these topics:

* Inflation Rates (Year Over Year)
* Consumer Price Index
* Gold & Silver Prices
* Bitcoin Price Provided By Blockchain.com
* Canadian Mortgage and Housing Corporation Prices
* Bitfinex Exchange For Crypto Price Data

&nbsp;

[Math Tools R Shiny Web Application](https://dkmathstats.shinyapps.io/mathTools/)

This RShiny project with `flexdashboard` features a collection of mathematics tools. 

The app has these math tools.

* Polynomial Functions Plotting Tool
* Line Plotter
* Trigonometric Functions Plotting Tool
* Geometry Calculators
* Compound Interest Calculator 
* Annual vs Weekly vs Monthly Wages Calculator
* Quadratic Formula Calculator

&nbsp;

[German Bundesliga Soccer Final Season Tables Application](https://dkmathstats.shinyapps.io/bundesligaTables_app/)

* This easy to use RShiny app uses the `BundesligR` package along with manual data collection for displaying the final season tables for the German Bundesliga soccer league from 1964 to the 2019-2020 seasons.
* Users can search for the final season tables by year or search for a team with the team picker to see how a team performed over the years.

&nbsp;


[Monte Carlo Simulation R Shiny App with shinydashboard For Estimating π](https://dkmathstats.shinyapps.io/monteCarlo_estimatePi/) 

* A simple application done with R, RShiny and the `shinydashboard` package. A Monte Carlo simulation is used to generate uniform random variables within a square to estimate the value of $\pi$.

&nbsp;
