---
title: "The Norm Of A Vector"
output: html_document
---

&nbsp;


This post will be about the norm of a vector. It is assumed that the reader knows about vectors where a vector in $\mathbb{R}^{n}$ is of the form $\textbf{v} = (v_1, v_2, \dots, v_{n})$.

&nbsp;

### <u>Definition Of A Norm</u>

&nbsp;

The norm of a vector $\textbf{v} = (v_1, v_2, \dots, v_{n})$ in $\mathbb{R}^{n}$ is defined as:

&nbsp;

$$ \displaystyle ||\textbf{v}|| = \sqrt{v_1^2 + v_2^2 + v_3^2 + \dots + v_{n}^2}$$

&nbsp;

Sometimes the norm of a vector $\textbf{v}$ is referred as the length of $\textbf{v}$ or the magnitude of $\textbf{v}.$

In three dimensions, a vector in $\mathbb{R}^{3}$ is $\textbf{v} = (v_1, v_2, v_{3})$ with the norm as:

&nbsp;

$$\displaystyle ||\textbf{v}|| = \sqrt{v_1^2 + v_2^2 + v_3^2}$$

&nbsp;

In two dimensions, we have a vector $\textbf{v} = (v_1, v_2)$ in $\mathbb{R}^{2}$. Its norm is:

&nbsp;

$$\displaystyle ||\textbf{v}|| = \sqrt{v_1^2 + v_2^2}$$
&nbsp;

In one dimension, we have a the vector $\textbf{v}$ is just $v$ on the real line $\mathbb{R}$. The absolute value is a special case of the norm and it is expressed as:

&nbsp;

$$\displaystyle ||\textbf{v}|| = \sqrt{v^{2}} = |v|$$
&nbsp;

Note that we square the number to ensure a positive number and then take the square root. Doing this is the same as taking the absolute value.

The norm is no longer a vector as it is a scalar/number (with no direction).

&nbsp;

### <u>Some Properties Of The Norm</u>

&nbsp;

Here are some properties of a vector $\textbf{v}$ in $\mathbb{R}^{n}$ with a scalar (real number) $k$.

&nbsp;

$$\displaystyle || \textbf{v}|| \geq 0$$

$$\displaystyle ||\textbf{v}|| = 0 \text{ if and only if (iff)} ||\textbf{v}|| = \textbf{0}$$

$$\displaystyle ||k \cdot \textbf{v}|| = |k| \cdot ||\textbf{v}||$$

&nbsp;

### <u>Unit Vectors</u>

A vector of a norm of 1 is a unit vector. Unit vectors are of use when length is not relevant. The unit vector $\textbf{u}$ is defined as:

&nbsp;

$$\displaystyle \textbf{u} = \dfrac{1}{|| \textbf{v}||} \cdot \textbf{v}$$

&nbsp;

where v is a non-zero vector in $\mathbb{R}^{n}$.

When we obtain a unit vector u from v, it is called normalizing v.

&nbsp;

**Example One**

Normalize the vector $\textbf{v} = (-3, 4)$.

Answer:

The norm of $\textbf{v} = (-3, 4)$ is:

&nbsp;

$$\displaystyle \begin{array} {lcl} || \textbf{v}|| & = & \sqrt{ (3)^2 + (-4)^2} \\ & = & \sqrt{9 + 16} \\ & = & \sqrt{25} \\ & = & 5 \\ \end{array} \\ $$

&nbsp;

The unit vector u with the same direction as v will be:

&nbsp;

$$\displaystyle \textbf{u} = \dfrac{1}{5} \cdot (-3, 4) = (-\dfrac{3}{5}, \dfrac{4}{5})$$
&nbsp;

---

**Example Two**

&nbsp;

Given the vector $\textbf{v} = (1, 5, -2)$. Find the unit vector u such that it has the same direction as v.

Answer:

The norm of $\textbf{v} = (1, 5, -2)$ is:

&nbsp;

$$\displaystyle \begin{array} {lcl} || \textbf{v}|| & = & \sqrt{ (1)^2 + (5)^2 + (-2)^2} \\ & = & \sqrt{1 + 25 + 4} \\ & = & \sqrt{30} \\ \end{array} $$

&nbsp;

Our unit vector u will be:

&nbsp;

$$\displaystyle \textbf{u} = \dfrac{1}{\sqrt{30}} \cdot (1, 5, -2) = (\dfrac{1}{\sqrt{30}}, \dfrac{5}{\sqrt{30}}, \dfrac{-2}{\sqrt{30}})$$

&nbsp;

### <u>Standard Unit Vectors</u>

You may encounter standard unit vectors (of norm 1) in the form of:

&nbsp;

$$\displaystyle \textbf{i} = (1, 0) \text{ and } \textbf{j} = (0, 1)$$

&nbsp;

in $\mathbb{R}^{2}$. For $\mathbb{R}^{3}$, you may see:

&nbsp;

$$\displaystyle \textbf{i} = (1, 0, 0) \text{ , } \textbf{j} = (0, 1, 0) \text{ and } \textbf{j} = (0, 0, 1)$$.

&nbsp;

For example, we can express the vector (2, 1) as $2 \cdot \textbf{i} + \textbf{j}$. Likewise, the vector (-3, -1, 5) can be expressed as $-3 \cdot \textbf{i} - \textbf{j} + 5 \cdot \textbf{k}$.

In the general case in $\mathbb{R}^{n}$, the standard unit vectors would be:

&nbsp;

$$ \displaystyle \textbf{e}_1 = (1, 0, 0, \dots , 0) $$

$$ \displaystyle \textbf{e}_2 = (0, 1, 0, \dots , 0) $$

$$ \displaystyle \textbf{e}_3 = (0, 0, 1, \dots , 0) $$

$$ \displaystyle \vdots$$

$$\displaystyle \textbf{e}_n = (0, 0, 0, \dots , n) $$

&nbsp;

and any vector $\textbf{v} = (v_1, v_2, \dots, v_{n})$ can be expressed as a linear combination as follows:

$$\displaystyle \textbf{v} = v_1 \cdot \textbf{e}_1 + v_2 \cdot \textbf{e}_2 + \dots + v_{n} \cdot \textbf{e}_n $$

&nbsp;

### <u>Distance Between Two Vectors</u>

&nbsp;

Recall that the distance between points $P_1(x_1, y_1)$ and $P_2(x_2, y_2)$ in 2-space is:

&nbsp;

$$\displaystyle d(\textbf{a}, \textbf{b}) = ||\overrightarrow{P_1 P_2}|| = \sqrt{ (x_2 - x_1)^2 + (y_2 - y_1)^2}$$

&nbsp;

In a three-dimensional setting, the distance between points $P_1(x_1, y_1, z_1)$ and $P_2(x_2, y_2, z_2)$ is:

&nbsp;

$$\displaystyle d(\textbf{a}, \textbf{b}) = ||\overrightarrow{P_1 P_2}|| = \sqrt{ (x_2 - x_1)^2 + (y_2 - y_1)^2 + (z_2 - z_1)^2}$$

&nbsp;

We can now extend this to n-th dimensional space $\mathbb{R}^{n}$.

In $\mathbb{R}^{n}$, the distance between vectors $\textbf{a} = (a_1, a_2, a_3, \dots, a_n)$ and $\textbf{b} = (b_1, b_2, b_3, \dots, b_n)$ is

$$\displaystyle d(\textbf{a}, \textbf{b}) = ||\textbf{a} - \textbf{b}|| = \sqrt{ (a_1 - b_1)^2 + (a_2 - b_2)^2 + (a_3 - b_3)^2 + \dots + (a_n - b_n)^2}$$

&nbsp;

---

**Example**

Calculate the distance between the vectors $\textbf{v} = (10, 5, -2, -1)$ and $\textbf{w} = (-1, 0, 2, 1)$ in $\mathbb{R}^{4}$.

Answer:

We apply the distance formula.

&nbsp;

$$\displaystyle \begin{array} {lcl} d(\textbf{v}, \textbf{w}) & = & \sqrt{ (v_1 - w_1)^2 + (v_2 - w_2)^2 + (v_3 - w_3)^2 + (v_4 - w_4)^2} \\ & = & \sqrt{ (10 - (-1))^2 + (5 - 0)^2 + (-2 - 2)^2 + (-1 - 1)^2} \\ & = & \sqrt{ (11)^2 + (5)^2 + (-4)^2 + (-2)^2} \\ & = & \sqrt{ 121 + 25 + 16 + 4} \\ & = & \sqrt{166} \\ & \approx & 12.8841 \text{ units} \\ \end{array} $$
&nbsp;

---

Reference: Elementary Linear Algebra (10th Editon) by Howard Anton

The image is taken from https://www.mathsisfun.com/algebra/images/vector-mag-dir.gif