---
title = "The Fibonacci Sequence"
---

&nbsp;

# <u>The Fibonacci Sequence</u>

&nbsp;

Hi. Here is a short guide on the Fibonacci sequence of numbers.

&nbsp;

A sequence is a list of ordered objects. In a lot of cases, sequences are lists of ordered numbers. One example of a sequence is the set of even numbers such as 2, 4, 6, 8, etc. The first term in the sequence is 2, the second term being 4 and so on.

&nbsp;

The Fibonacci sequence starts with the first two terms being 1 and 1 (or 0 and 1 as an alternate version). The third term would be the sum of the previous two terms which would be $1 + 1 = 2$. The next term would be $1 + 2 = 3$. The term after the 3 would be $3 + 2 = 5$. The pattern continues by adding the previous two terms together to get the next term.

&nbsp;

The Fibonacci sequence of numbers is an infinite (never-ending) sequence of numbers. Here are the first 10 terms of the Fibonacci sequence.

&nbsp;

$$1, 1, 2, 3, 5, 8, 13, 21, 34, 55, ...$$

&nbsp;



## The Fibonacci Number Sequence (Simplified)

&nbsp;

1) Start with the numbers 1 and 1 (or 0 and 1) as the first two terms (Base Case).

2) Add the previous two terms together to obtain the next term in the sequence.

&nbsp;



## The Fibonacci Number Sequence (Mathematical Version)

Assume that $a_{n}$ for $n = \{1, 2, 3, ...\}$ is the n-th term in the Fibonacci sequence. For example we have $a_{1} = 1$ and $a_{5} = 5$.

&nbsp;

1) Start with $a_{1} = 1$ and $a_{2} = 1$ (or $a_{1} = 0$ and $a_{2} = 1$) as the first two terms.

&nbsp;

2) For $j = \{3, 4, ...\}$, the next term $a_{j}$ can be obtained using the formula $a_{j} = a_{j - 1} + a_{j - 2}$.
