---
title: "Math Tutoring In Toronto"
output: html_document
---

&nbsp;

Hi there. I am open to providing math tutoring services in Toronto. 


If you are interested in math tutoring services please e-mail me at dku8691@protonmail.com. It would be preferred to have a detailed e-mail title requesting for math tutoring in the Toronto area.


&nbsp;

**As Of August 2019 onwards**

In terms of location, I would prefer to meet in a public area such as a library, coffee shop, etc. If you insist on tutoring inside your home then that is okay. Locations of interest for me would be near Yorkdale Mall or The University Of Toronto campus.

For now I can only do Sundays (let me know when on Sundays).

Pricing: $40 CAD / Hour or $30 for 45 Minutes.

&nbsp;

---

## <u>Math Tutoring Topics</u>


&nbsp;

**University Level**

For the courses with (Maybe), I can tutor in these subjects but I would need some review.

<u>First Year Courses</u>

* Introductory Calculus 
* Introduction To Mathematics For Finance
* Introductory Probability & Statistics
* Introductory Linear Algebra 

&nbsp;

<u>Upper Year Courses</u>

* Probability Theory (Maybe)
* Introduction To Stochastic Calculus (Maybe)
* Stochastic Calculus For Finance (Maybe)

&nbsp;

**High School Level**

* Grade 12 Data Management
* Grade 12 Calculus & Vectors
* Grade 12 Advanced Functions
* Grade 9 - 11 Mathematics

&nbsp;

**<u>Middle School Level**</u>

* Grade 6 to 8 Mathematics with topics in algebra, order of operations, probability.

&nbsp;

---

## <u>My Math Tutoring Resume</u>


&nbsp;
	
### Education

&nbsp;

**Master of Science In Statistics 
McMaster University, Hamilton, ON**                                 
2013 – 2015

**Bachelor of Arts Financial Mathematics
Wilfrid Laurier University, Waterloo, ON**         
2009 – 2013              

&nbsp;

---

### Math Tutoring & Assistance History

&nbsp;

**Graduate Teaching Assistant for Mathematics                                       - McMaster University, Hamilton, ON**      
Sept. 2013 - Dec. 2014 

◦ Assisted first year science & engineering students with math software for introductory calculus & linear algebra courses.

&nbsp;

**Undergraduate Instructional Assistant                                          - Wilfrid Laurier University, Waterloo, ON**      
Jan. 2011 – June 2013 

* MA100 Calculus For Natural Sciences I
* MA101 Calculus For Natural Sciences II
* MA170 Introduction To Mathematics For Finance
* MA104 Calculus II
* MA241 Statistical Methods For Life Sciences

&nbsp;

**Peer Tutor – Mathematics Asssistance Centre                                         - Wilfrid Laurier University, Waterloo, ON**  
Jan. 2011 – June 2012

Assisted students in these subjects:

* MA100 Calculus For Natural Sciences I
* MA101 Calculus For Natural Sciences II
* MA103 Calculus I
* MA104 Calculus II
* MA170 Introduction To Mathematics For Finance
* MA121 Introduction To Mathematical Proofs
* MA122 Introductory Linear Algebra
* Introductory Probability & Statistics




