---
title = "Working With Exponents"
---

&nbsp;

# <u>Working With Exponents</u>

&nbsp;

Hi. This page will be about exponent laws and algebra. This guide is more suited for a high school audience and can be used as a refresher for pre-calculus and calculus students.

&nbsp;

### Table Of Contents


&nbsp;

* What Is An Exponent?
* Exponent Laws
* Notes
* Examples
* Practice Problems
* Answers

&nbsp;

### What Is An Exponent?


&nbsp;

Suppose I want to multiply the number 2 by itself 4 times. I can write this as $2 \times 2 \times 2 \times 2$. If I wanted to multiply 2 by itself 20 times, that would take up a lot of space. Instead of doing $2 \times 2 \times 2 \times 2 ... \times 2$ with 20 twos and 19 multiplication signs we can expressed this as $2^{20}$. The 2 is a base while the superscripted number 20 is the exponent.

If I wanted to multiply 5 by itself 4 times I can write $5 \times 5 \times 5 \times 5$ or simply $5^{4} = 625$. The 4 here is like a counter of how many times the base number 5 is multiplied by itself. An alternate view would be $25 \times 25 = 5^{2} \times 5^{2} = 5^{4} = 625$. In this case I can add the exponents 2 and 2 to get 4 as long as the bases are the same.

&nbsp;

### Exponent Laws


Mathematics contains a lot of rules (axioms). Some could say that mathematics is like a language. Here are the rules/laws of exponents. ($m$ and $n$) are typically whole numbers)

&nbsp;

**Multiplying Numbers of The Same Base**

&nbsp;

$$a^{m} \times a^{n} = a^{m + n}$$

&nbsp;

**Dividing Numbers of The Same Base**

&nbsp;

$$\dfrac{a^{m}}{a^{n}} = a^{m - n}$$

&nbsp;

**Power of A Power (Power Rule)**

&nbsp;

$$(a^{m})^{n} = a^{mn}$$

&nbsp;

**Zero Exponent**

&nbsp;

$$a^{0} = 1$$

&nbsp;

because $\dfrac{a^{m}}{a^{m}} = a^{m - m} = a^{0} = 1$

&nbsp;

**Negative Exponents**

&nbsp;

$$a^{-m} = \dfrac{1}{a^m} \text{ and }\dfrac{1}{a^{-m}} = a^{m}$$

&nbsp;

**Negative Exponents (Version 2)**

&nbsp;

$$ab^{-m} = \dfrac{a}{b^m} \text{ and } \dfrac{a}{b^{-m}} = ab^{m}$$

&nbsp;

### Notes


&nbsp;

There are times when you may have to apply multiple exponent laws. For example we could have $(\dfrac{a}{b^{2}})^{-2} = (\dfrac{b^2}{a})^{2} = \dfrac{(b^2)^{2}}{a^2} = \dfrac{b^4}{a^2}$. This example applies the negative exponent then the power rule.

&nbsp;

It is important to note that that $(ab)^2 = a^{2}b^{2}$ which is different from $ab^2$. The exponent 2 is applied to $ab$ inside the bracket in $(ab)^2$ while the exponent 2 is applied to only $b$ in $ab^2$.

&nbsp;

In general, the n$^{th}$ root $\sqrt[n]{x} = x^{1/n}$. With a square root you would have $n = 2$.

&nbsp;

Recall that $\dfrac{a}{b} \div \dfrac{c}{d} = \dfrac{a}{b} \times \dfrac{d}{c}$. A special case of this would be $\dfrac{1}{1} \div \dfrac{1}{a} = 1 \div \dfrac{1}{a} = 1 \times \dfrac{a}{1} = 1 \times a = a$.

&nbsp;


### Examples


Here are some examples using various exponent laws.

&nbsp;

**Example One**

Convert $\dfrac{x^{-2}y^2}{z^{-1}}$ from negative exponents to positive exponents.

&nbsp;

Answer:

$$\dfrac{x^{-2}y^2}{z^{-1}} = y^2 \times \dfrac{1}{\dfrac{1}{z}} \times \dfrac{1}{x^2} = y^2 \times z \times \dfrac{1}{x^2} = \dfrac{y^2z}{x^2} $$

&nbsp;

**Example Two**

Simplify $\dfrac{x^2}{y^{-5}} \times \dfrac{x^3}{y^2}$.

&nbsp;

Answer:

$$\dfrac{x^2}{y^{-5}} \times \dfrac{x^3}{y^2} = x^{2 + 3} \times y^5 \times \dfrac{1}{y^2} = x^{5} \times \dfrac{y^5}{y^2} = x^5y^{5 - 2} = x^{5}y^{3}$$

&nbsp;

**Example Three**

Evaluate $(\dfrac{2}{3})^{-2}$.

&nbsp;

Answer:

$$(\dfrac{2}{3})^{-2} = (\dfrac{3}{2})^{2} = \dfrac{3^2}{2^2} = \dfrac{9}{4} \text{ or } 2\dfrac{1}{4}$$

&nbsp;

### Practice Problems


Here are some practice problems to test your understanding and build your skills. The answers are in the next section.

&nbsp;

1) Convert $x^{-2}y^{-10}$ from negative exponents to positive exponents.

2) Evaluate $(\dfrac{2}{5})^{-3}$.

3) Convert $\dfrac{x^{-1}}{z^{-2}}$ from negative exponents to positive exponents.

4) Convert the fractions $\dfrac{1}{x^4}$ and $\dfrac{2}{y^3}$ into non-fractions with negative exponents.

5) Simplify $\dfrac{x^3y^{-2}}{x^7y}$.

6) Simplify $(\dfrac{x^8}{y^2})^{1/2}$.

7) Evaluate $(\dfrac{100}{9})^{-1/2}$.

&nbsp;

### Answers


1) $x^{-2}y^{-10} = \dfrac{1}{x^{2}y^{10}}$

2) $\dfrac{2}{5})^{-3} = (\dfrac{5}{2})^{3} = \dfrac{5^3}{2^3} = \dfrac{125}{8} = 15.625$

3) $\dfrac{x^{-1}}{z^{-2}} = \dfrac{z^2}{x}$

4) $\dfrac{1}{x^4} = x^{-4}$ and $\dfrac{2}{y^3} = 2y^{-3}$

5) $\dfrac{x^3y^{-2}}{x^7y} = x^{3 -7}y^{-2 - 1} = x^{-4}y^{-3} \text{ or } \dfrac{1}{x^4y^3}$

6) $(\dfrac{x^8}{y^2})^{1/2} = \dfrac{(x^{8})^{1/2}}{(y^2)^{1/2}} = \dfrac{x^{8/2}}{y^{2/2}} = \dfrac{x^4}{y}$

7) $(\dfrac{100}{9})^{-1/2} = (\dfrac{9}{100})^{1/2} = \dfrac{9^{1/2}}{100^{1/2}} = \dfrac{\sqrt{9}}{\sqrt{100}} = \dfrac{3}{10}$
