---
title: "Python Programming"
output: html_document
---

&nbsp;

This page contains a list of Python programming projects.

&nbsp;

# <u>Categories</u>

&nbsp;


* <a href="#mathstats">Math And Stats In Python</a>

* <a href="#visual">Data Visualization In Python</a>

* <a href="#crypto">Crypto Projects In Python</a>

&nbsp;


<a name="mathstats"></a>

### <u>Math And Stats In Python</u>

&nbsp;

* [Arithmetic Sequences & Series In Python](https://github.com/dk81/python_math/blob/master/arithmeticSeries.py)

* [Mean, Median, Mode & Variance In Python](https://github.com/dk81/python_math/blob/master/mean_medianMode.py)

* [Brownian Motion Plot In Python](https://github.com/dk81/python_math/blob/master/brownianMotion.py)

* [The Bisection Method In Python](https://github.com/dk81/python_math/blob/master/bisection_method.py)

* [Linear Algebra With Python & Numpy](https://github.com/dk81/python_math/blob/master/numpy_linearalgebra_work.py)

* [Sum Of Mario Party Dice](https://github.com/dk81/python_math/blob/master/sum_MarioParty_dice.ipynb)

* [Random Walk Plots In Python](https://github.com/dk81/python_math/blob/master/randomWalk.py)

&nbsp;

<a name="visual"></a>

### <u>Data Visualization In Python</u>

&nbsp;

* [Histograms In Python](https://github.com/dk81/python_datavisualization/blob/master/histograms.ipynb)

* [Bar Graphs In Python](https://github.com/dk81/python_datavisualization/blob/master/barGraphs.ipynb)

* [A Pie Chart In Python](https://github.com/dk81/python_datavisualization/blob/master/pieChart.ipynb)

* [Plots With Python & Seaborn](https://github.com/dk81/python_datavisualization/blob/master/seaborn-plots.ipynb)

* [A Rock, Paper, Scissors Table Plot In Python](https://github.com/dk81/python_datavisualization/blob/master/rock-paper-scissors.ipynb)

* [A Rock, Paper, Scissors, Lizard, Spock Table Plot In Python](https://github.com/dk81/python_datavisualization/blob/master/rock-paper-scissors-lizard-spock.ipynb)

* [A Pokemon Types Table In Python](https://github.com/dk81/python_datavisualization/blob/master/pokemon-types-table.ipynb)


&nbsp;

<a name="crypto"></a>

### <u>Crypto Projects In Python</u>

&nbsp;


[Binance For Crypto Data & Candlestick Charts In Python](https://github.com/dk81/crypto_python/blob/main/binance_crypto_data.ipynb)

The python-binance package along with mplfinance was used to obtain cryptocurrency information from Binance. A candlestick price chart for the BTCUSDT trading pair was produced. 

&nbsp;

[Kucoin Crypto Data & Candlestick Charts In Python](https://github.com/dk81/crypto_python/blob/main/kucoin_crypto_python.ipynb)

This project is similar to the Binance crypto data project. The Kucoin crypto exchange API is used to connect to Python. Candlestick price charts are produced with the mplfinance Python library.

&nbsp;

[Coinbase Crypto Data In Python & Candlestick Price Charts](https://github.com/dk81/crypto_python/blob/main/coinbase_cryptodata_python.ipynb)

Python being used to extract Coinbase crypto price data with the Coinbase API.

&nbsp;

[Crypto Fear & Greed Index Data In Python](https://github.com/dk81/crypto_python/blob/main/feargreed_stockscrypto.ipynb)

Using Python to extract cryptocurrency fear and greed index data and plotting the index values in a line plot.

&nbsp;


[Bitcoin Line Plots On Price & Marketcap In Python](https://github.com/dk81/crypto_python/blob/main/bitcoin_price_mcap_plots.ipynb)

Python and plotly to plot simple line plots on Bitcoin's historical price and marketcap.

&nbsp;

[Yahoo Finance For Stocks & Crypto In Python](https://github.com/dk81/crypto_python/blob/main/yahoo_finance_python_stocks_crypto.ipynb)

Exploring the `yfinance` package in Python and plotting prices of stocks & cryptocurrency.

&nbsp;

[Coingecko Price Data Webscrape In Python](https://github.com/dk81/crypto_python/blob/main/coingecko_crypto_webscrape.ipynb)

Using Python and BeautifulSoup to webscrape cryptocurrency prices from the Coingecko website.


&nbsp;