<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Producing Histograms In R</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/detect-resize-0.5.3/jquery.resize.js"></script>
<link href="site_libs/jquery-ui-1.11.4/jquery-ui.min.css" rel="stylesheet" />
<script src="site_libs/jquery-ui-1.11.4/jquery-ui.min.js"></script>
<script src="site_libs/d3-3.5.2/d3.min.js"></script>
<script src="site_libs/vega-1.4.3/vega.min.js"></script>
<script src="site_libs/lodash-2.2.1/lodash.min.js"></script>
<script>var lodash = _.noConflict();</script>
<link href="site_libs/ggvis-0.4.3/css/ggvis.css" rel="stylesheet" />
<script src="site_libs/ggvis-0.4.3/js/ggvis.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}

.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">dkmathstats Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="mathstats_pages.html">Math &amp; Stats Pages</a>
</li>
<li>
  <a href="r-projects.html">R Programming</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Producing Histograms In R</h1>

</div>


<p> </p>
<p>Hi there. In this post, I will highlight histograms in the statistical program R using the R base package, ggvis and the ggplot2 data visualization packages. (Note: This is a long post.)</p>
<p> </p>
<div id="table-of-contents" class="section level3">
<h3><u>Table Of Contents</u></h3>
<p> </p>
<ul>
<li><a href="#dataset">The Dataset: Time Spent On Facebook</a></li>
<li><a href="#load">Loading The Data and Summary Statistics</a></li>
<li><a href="#extract">Extracting Information From The Dataset</a></li>
<li><a href="#base">Histogram Example Using Base R</a></li>
<li><a href="#ggvis">A ggvis Histogram Example</a></li>
<li><a href="#ggplot2">Histograms Using ggplot2</a></li>
<li><a href="#notes">Notes, Thoughts, Analyses</a></li>
<li><a href="#refs">References</a></li>
</ul>
<p> </p>
<p><a name="dataset"></a></p>
</div>
<div id="the-dataset-time-spent-on-facebook" class="section level3">
<h3><u>The Dataset: Time Spent On Facebook</u></h3>
<p>This dataset was found from the link:</p>
<p><a href="http://sites.williams.edu/bklingen/files/2015/07/timeFB.csv" class="uri">http://sites.williams.edu/bklingen/files/2015/07/timeFB.csv</a></p>
<p>It is a .csv file that can be read in Excel or a notepad program such as Notepad++. Since this is a .csv file this works well with R (Python and other programs).</p>
<p>There are two columns in the dataset which are class and time. There is no other information included (there was no description of the dataset found on the website). I am going to assume the times in the second column are in minutes (per week). It is unknown what FR, JU, SE and SO are under the class column of the dataset.</p>
<p> </p>
<p><a name="load"></a></p>
</div>
<div id="loading-the-data-and-summary-statistics" class="section level3">
<h3><u>Loading The Data and Summary Statistics</u></h3>
<p> </p>
<p>We will load the data into R from the web. You can also download the .csv file into a folder and have R load the file from a directory. But I think it is much easier to load files from the web (when possible).</p>
<p> </p>
<pre class="r"><code># The url link of the dataset in .csv format:

url = &#39;http://sites.williams.edu/bklingen/files/2015/07/timeFB.csv&#39;

# Load data with read.csv() function with header = TRUE

facebook_time &lt;- read.csv(url, header = TRUE)</code></pre>
<p> </p>
<p>In the read.csv function, we put <code>header = TRUE</code> so that R recognizes the column titles as column titles and not as observations in the data set.</p>
<p> </p>
<p><strong>Summary Statistics</strong></p>
<p> </p>
<p>After loading the data in, we want to take a look at our data, its size dimensions and some summary statistics.</p>
<p>The <code>head()</code> function takes a look of the first six rows of the dataset. (One could use the n = argument to look at more/less rows)</p>
<p>The <code>str()</code> function gives us the structure of the dataset with information of values, variables, factors and so forth.</p>
<p>Summary() in R gives us summary statistics such as mean, median, counts, minimum, maximums and so forth. There is no built-in mode function in R. One can refer to a previous post here.</p>
<p>The R code and output for this part is as follows:</p>
<p> </p>
<pre class="r"><code># A look at the data:

head(facebook_time)</code></pre>
<pre><code>##   class FBtime
## 1    FR     60
## 2    FR      0
## 3    FR     60
## 4    FR      0
## 5    FR      0
## 6    FR      0</code></pre>
<pre class="r"><code>str(facebook_time)</code></pre>
<pre><code>## &#39;data.frame&#39;:    1597 obs. of  2 variables:
##  $ class : Factor w/ 4 levels &quot;FR&quot;,&quot;JU&quot;,&quot;SE&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ FBtime: num  60 0 60 0 0 0 0 30 7.5 45 ...</code></pre>
<p> </p>
<p>From the <code>str()</code> output we have 2 variables/columns which are class and time with 1597 observations.</p>
<p>Notice that the <code>summary()</code> function gives counts under the class variable/column as FR, JU, SE, SO are not variables.</p>
<p>In a sorted sequence of values/numbers from lowest to highest, the 1st Quartile is the 25th percentile, the Mode (not given) is the 50th percentile or just simply the middle number, and the 3rd quartile is the 75th percentile.</p>
<p> </p>
<p><a name="extract"></a></p>
</div>
<div id="extracting-information-from-the-dataset" class="section level3">
<h3><u>Extracting Information From The Dataset</u></h3>
<p> </p>
<p>Sometimes the mean, median and mode metrics are not enough (or not understood). What if we wanted to know the amount of users from the 1597 who spend a certain amount of time on Facebook? The code and output is below.</p>
<p> </p>
<pre class="r"><code># The times are in the second column

fb_time &lt;- facebook_time[, 2]

# Users who spend no time on facebook:

no_fb &lt;- sum(fb_time == 0); no_fb</code></pre>
<pre><code>## [1] 336</code></pre>
<pre class="r"><code># Percentage/Proportion out of 1597 observations:

no_fb / 1597</code></pre>
<pre><code>## [1] 0.2103945</code></pre>
<pre class="r"><code># Users less than 30 minutes:

less30_fb &lt;- sum(fb_time &lt; 30); less30_fb; less30_fb / 1597</code></pre>
<pre><code>## [1] 659</code></pre>
<pre><code>## [1] 0.4126487</code></pre>
<pre class="r"><code># Users from at least 30 minutes to an hour (non - inclusive):

fb_30_hour &lt;- sum(fb_time &gt;= 30 &amp; fb_time &lt; 60); fb_30_hour; fb_30_hour / 1597</code></pre>
<pre><code>## [1] 301</code></pre>
<pre><code>## [1] 0.1884784</code></pre>
<pre class="r"><code># At least an hour on facebook:

hourplus_fb &lt;- sum(fb_time &gt;= 60); hourplus_fb; hourplus_fb / 1597</code></pre>
<pre><code>## [1] 637</code></pre>
<pre><code>## [1] 0.3988729</code></pre>
<p> </p>
<p>The amount of users from the 1597 who spend no time on Facebook is 336 or about 21.04% of the 1597 in the sample.</p>
<p>The amount of users who spend less than 30 minutes on Facebook is 659 or about 41.26% of the 1597 in the sample.</p>
<p>The amount of users who spend at least 30 minutes but less than an hour on Facebook is 301 or about 18.85% of the 1597.</p>
<p>From the 1597, we have 637 or about 39.89% who spend at least an hour on Facebook.</p>
<p> </p>
<p><a name="base"></a></p>
</div>
<div id="histogram-example-using-base-r" class="section level3">
<h3><u>Histogram Example Using Base R</u></h3>
<p> </p>
<p>We use the <code>hist()</code> function from the base package in R to produce a histogram.</p>
<p> </p>
<pre class="r"><code># Base R Package Histogram:

hist(fb_time, xlab = &quot;Time Spent on Facebook (Min.)&quot;, ylab = &quot;Number of Facebook Users&quot;,
 main = &#39;Facebook Activity&#39;, ylim = c(0, 1100))</code></pre>
<p><img src="rvisual-histograms_files/figure-html/unnamed-chunk-4-1.png" width="384" /></p>
<p> </p>
<p>This histogram gives us what we need but it looks bland and outdated.</p>
<p> </p>
<p><a name="ggvis"></a></p>
</div>
<div id="a-ggvis-histogram-example" class="section level3">
<h3><u>A ggvis Histogram Example</u></h3>
<p>We explore graphing using the ggvis package to produce a more appealing histogram.</p>
<p>The packages ggvis and dplyr (for the %&gt;%, I won’t explain details) in R will be used. My code and output is below.</p>
<p> </p>
<pre class="r"><code>library(ggvis)
library(dplyr)

facebook_time %&gt;% ggvis(~fb_time) %&gt;% layer_histograms() %&gt;%
  add_axis(&quot;x&quot;, title = &quot;Time Spent on Facebook (Min.)&quot;, title_offset = 50) %&gt;%
  add_axis(&quot;y&quot;, title = &quot;Number of Facebook Users&quot;, title_offset = 50)</code></pre>
<pre><code>## Guessing width = 20 # range / 24</code></pre>
<div id="plot_id925492887-container" class="ggvis-output-container">
<div id="plot_id925492887" class="ggvis-output"></div>
<div class="plot-gear-icon">
<nav class="ggvis-control">
<a class="ggvis-dropdown-toggle" title="Controls" onclick="return false;"></a>
<ul class="ggvis-dropdown">
<li>
Renderer: 
<a id="plot_id925492887_renderer_svg" class="ggvis-renderer-button" onclick="return false;" data-plot-id="plot_id925492887" data-renderer="svg">SVG</a>
 | 
<a id="plot_id925492887_renderer_canvas" class="ggvis-renderer-button" onclick="return false;" data-plot-id="plot_id925492887" data-renderer="canvas">Canvas</a>
</li>
<li>
<a id="plot_id925492887_download" class="ggvis-download" data-plot-id="plot_id925492887">Download</a>
</li>
</ul>
</nav>
</div>
</div>
<script type="text/javascript">
var plot_id925492887_spec = {
  "data": [
    {
      "name": ".0/bin1/stack2",
      "format": {
        "type": "csv",
        "parse": {
          "xmin_": "number",
          "xmax_": "number",
          "stack_upr_": "number",
          "stack_lwr_": "number"
        }
      },
      "values": "\"xmin_\",\"xmax_\",\"stack_upr_\",\"stack_lwr_\"\n-10,10,477,0\n10,30,341,0\n30,50,132,0\n50,70,138,0\n70,90,172,0\n90,110,30,0\n110,130,65,0\n130,150,83,0\n150,170,15,0\n170,190,57,0\n190,210,12,0\n210,230,16,0\n230,250,19,0\n250,270,10,0\n270,290,0,0\n290,310,16,0\n310,330,6,0\n330,350,1,0\n350,370,3,0\n370,390,0,0\n390,410,0,0\n410,430,1,0\n430,450,0,0\n450,470,0,0\n470,490,3,0"
    },
    {
      "name": "scale/x",
      "format": {
        "type": "csv",
        "parse": {
          "domain": "number"
        }
      },
      "values": "\"domain\"\n-35\n515"
    },
    {
      "name": "scale/y",
      "format": {
        "type": "csv",
        "parse": {
          "domain": "number"
        }
      },
      "values": "\"domain\"\n0\n500.85"
    }
  ],
  "scales": [
    {
      "name": "x",
      "domain": {
        "data": "scale/x",
        "field": "data.domain"
      },
      "zero": false,
      "nice": false,
      "clamp": false,
      "range": "width"
    },
    {
      "name": "y",
      "domain": {
        "data": "scale/y",
        "field": "data.domain"
      },
      "zero": false,
      "nice": false,
      "clamp": false,
      "range": "height"
    }
  ],
  "marks": [
    {
      "type": "rect",
      "properties": {
        "update": {
          "stroke": {
            "value": "#000000"
          },
          "fill": {
            "value": "#333333"
          },
          "x": {
            "scale": "x",
            "field": "data.xmin_"
          },
          "x2": {
            "scale": "x",
            "field": "data.xmax_"
          },
          "y": {
            "scale": "y",
            "field": "data.stack_upr_"
          },
          "y2": {
            "scale": "y",
            "field": "data.stack_lwr_"
          }
        },
        "ggvis": {
          "data": {
            "value": ".0/bin1/stack2"
          }
        }
      },
      "from": {
        "data": ".0/bin1/stack2"
      }
    }
  ],
  "legends": [],
  "axes": [
    {
      "type": "x",
      "scale": "x",
      "orient": "bottom",
      "title": "Time Spent on Facebook (Min.)",
      "titleOffset": 50,
      "layer": "back",
      "grid": true
    },
    {
      "type": "y",
      "scale": "y",
      "orient": "left",
      "title": "Number of Facebook Users",
      "titleOffset": 50,
      "layer": "back",
      "grid": true
    }
  ],
  "padding": null,
  "ggvis_opts": {
    "keep_aspect": false,
    "resizable": true,
    "padding": {},
    "duration": 250,
    "renderer": "svg",
    "hover_duration": 0,
    "width": 384,
    "height": 384
  },
  "handlers": null
};
ggvis.getPlot("plot_id925492887").parseSpec(plot_id925492887_spec);
</script>
<p> </p>
<p>This histogram looks much better and more polished.</p>
<p> </p>
<p><a name="ggplot2"></a></p>
</div>
<div id="histograms-using-ggplot2" class="section level3">
<h3><u>Histograms Using ggplot2</u></h3>
<p> </p>
<p>After learning about the ggplot2 package in R and playing around with it for the last few weeks, I prefer to graph using this.</p>
<p>For a simple plot with minimal code, the <code>qplot()</code> in ggplot2 is nice and simple.</p>
<p> </p>
<pre class="r"><code># ggplot2 qplot:

library(ggplot2)

qplot(fb_time, data = facebook_time, geom = &quot;histogram&quot;, binwidth = 50)</code></pre>
<p><img src="rvisual-histograms_files/figure-html/unnamed-chunk-6-1.png" width="384" /></p>
<p> </p>
<p><strong>ggplot2 Histograms</strong></p>
<p> </p>
<p>We can use more features from the ggplot2 package when it comes to data visualization. I do not want to go into details about the code. Code details can be found in the References at the bottom of this post. The code with comments and output are below.</p>
<p> </p>
<pre class="r"><code># ggplot2 histogram plots:

ggplot(facebook_time, aes(fb_time)) + geom_histogram(binwidth = 50) +
 labs(x = &quot;Time Spent on Facebook (Min.)&quot;, y = &quot;Number of Facebook Users&quot;) +
 theme(axis.text.x=element_text(angle=50, size=10, vjust=0.5))</code></pre>
<p><img src="rvisual-histograms_files/figure-html/unnamed-chunk-7-1.png" width="384" /></p>
<p> </p>
<pre class="r"><code># Adding colour outline of the bars (col = &quot;green&quot;):

ggplot(facebook_time, aes(fb_time)) + geom_histogram(binwidth = 50, col = &quot;green&quot;) +
 labs(x = &quot;Time Spent on Facebook (Min.)&quot;, y= &quot;Number of Facebook Users&quot;) +
 theme(axis.text.x=element_text(angle=50, size=10, vjust=0.5))</code></pre>
<p><img src="rvisual-histograms_files/figure-html/unnamed-chunk-8-1.png" width="384" /></p>
<p> </p>
<pre class="r"><code># Adding colour of the bars (fill = &quot;blue&quot;):

ggplot(facebook_time, aes(fb_time)) + geom_histogram(binwidth = 50, fill = &quot;blue&quot;) +
 labs(x = &quot;Time Spent on Facebook (Min.)&quot;, y= &quot;Number of Facebook Users&quot;) +
 theme(axis.text.x=element_text(angle=50, size=10, vjust=0.5))</code></pre>
<p><img src="rvisual-histograms_files/figure-html/unnamed-chunk-9-1.png" width="384" /></p>
<p> </p>
<pre class="r"><code># Making the bars lighter (alpha = 0.5):

ggplot(facebook_time, aes(fb_time)) + geom_histogram(binwidth = 50, fill = &quot;blue&quot;, alpha = 0.5) +
  labs(x = &quot;Time Spent on Facebook (Min.)&quot;, y= &quot;Number of Facebook Users&quot;) +
  theme(axis.text.x=element_text(angle=50, size=10, vjust=0.5))</code></pre>
<p><img src="rvisual-histograms_files/figure-html/unnamed-chunk-10-1.png" width="384" /></p>
<p><a name="notes"></a></p>
<p> </p>
</div>
<div id="notes-thoughts-analyses" class="section level3">
<h3><u>Notes, Thoughts, Analyses</u></h3>
<p> </p>
<p>With major thanks to the open source community and to those who have built great packages for R, displaying data does not have to be bland. The R packages ggvis and ggplot2 are very good for displaying histograms and data in general.</p>
<p>Notice that each bar represents a binwidth of 50. The first bin is from 0 to 50 minutes spent on Facebook. The data is skewed right as most of the values (or the peaks) are on the left and the tail (flat parts) of the frequency distribution is on the right.</p>
<p>Keep in mind that 1597 observations are in the sample. If we were to draw another 1597 observations, we may not get the exact same histogram (Frequentist statistics philosophy).</p>
<p><a name="refs"></a></p>
<p> </p>
</div>
<div id="references" class="section level3">
<h3><u>References</u></h3>
<p> </p>
<ul>
<li>Dataset: ‘<a href="http://sites.williams.edu/bklingen/files/2015/07/timeFB.csv" class="uri">http://sites.williams.edu/bklingen/files/2015/07/timeFB.csv</a>’</li>
<li><a href="http://docs.ggplot2.org/0.9.3.1/geom_histogram.html" class="uri">http://docs.ggplot2.org/0.9.3.1/geom_histogram.html</a></li>
<li><a href="http://zevross.com/blog/2014/08/04/beautiful-plotting-in-r-a-ggplot2-cheatsheet-3/" class="uri">http://zevross.com/blog/2014/08/04/beautiful-plotting-in-r-a-ggplot2-cheatsheet-3/</a></li>
<li>Datacamp courses were helpful in helping me discover and enjoy R again. There is more to R and statistical computing than just analyzing data and making statistical recommendations.</li>
<li>Featured image:<a href="http://onlinestatbook.com/2/graphing_distributions/histogram_files/image001.jpg" class="uri">http://onlinestatbook.com/2/graphing_distributions/histogram_files/image001.jpg</a></li>
</ul>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
