---
title: "Toronto Math Tutoring"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

&nbsp;

Hi there. If you are in the Toronto area and are in need of mathematics tutoring, I am available. I am currently near Yorkdale Mall (North York) and can travel to the Downtown area, the Annex area (Bathurst) and the east end (Danforth) of Toronto. 

My contact e-mail is dku8691@protonmail.com. It would be appreciated if there was a subject line that mentions math tutoring in the Toronto area. 

You can find my math tutoring history below.

&nbsp;

---

**Math Tutoring/Teaching History & Experience**

&nbsp;

I've started math tutoring when I was in grade ten when I tutored a classmate for volunteer hours. (Volunteer hours were needed to graduate high school.) I got good at it over time and it became a side thing.

---

&nbsp;

**Wilfrid Laurier University - Undergraduate Teaching Assistant**

Courses

* Calculus For Natural Sciences
* Calculus II (Seqeuences, Series, Integrals, Trigonometric Substitution)
* Introduction To Mathematics For Finance (Time Value Of Money, Annuities, Bonds)
* Introductory Statistics For Life Sciences

&nbsp;

**Wilfrid Laurier University - Math Assistance Centre Peer Tutor**

Knowledgeable In The Subjects Of

* Introductory Calculus
* Introduction To Mathematical Proofs
* Introductory Linear Algebra
* Introduction To Mathematics For Finance

&nbsp;

**Kumon Mathematics Instructor (Summer 2013)**

&nbsp;

**McMaster University - Graduate Teaching Assistant**

Courses

* Calculus I & II For Science & Engineering Students
* Linear Algebra For Science & Engineering Students
* Also worked with aiding students with math computing software such as Maple and MATLAB.

&nbsp;

**Various High School Mathematics Tutoring Roles**

- One student with Grade Twelve Advanced Functions
- Another student with Grade 10, 11 and 12 Mathematics






---

&nbsp;

Please contact me at my e-mail at dku8691@protonmail.com if you are interested.